version: "3.6"

services:
  inventory-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory:latest
    container_name: inventory
    environment:
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_HOSTNAME: $DATABASE_HOSTNAME
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_NAME: $DATABASE_NAME
    restart: on-failure
    ports:
      - "8000:8000"
    expose:
      - 8000

  inventory-app-ui:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    image: inventory-ui:latest
    container_name: inventory-ui
    environment:
      REACT_APP_BACKEND_URL: $REACT_APP_BACKEND_URL
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - inventory-app
