version: "3"

services:
  postgres-db:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
      # POSTGRES_PASSWORD_FILE: /run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
    ports:
      - "5433:5432"
    expose:
      - 5432
#    volumes:
#      - postgres-data:/var/lib/postgresql/data/
    restart: always

  pgadmin:
    container_name: "pgAdmin4"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    ports:
      - "5000:80"
      - "5001:443"
    expose:
      - 5000
      - 5001
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-db

  inventory-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory:latest
    container_name: inventory
    depends_on:
      - postgres-db
    environment:
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_HOSTNAME: $DATABASE_HOSTNAME
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_NAME: $DATABASE_NAME
    restart: on-failure
    ports:
      - "8000:8000"
    expose:
      - 8000

  inventory-app-ui:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    image: inventory-ui:latest
    container_name: inventory-ui
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - inventory-app

volumes:
  pgadmin-data:
  postgres-data: