version: "3"

services:
  postgres-db:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory
      # POSTGRES_PASSWORD_FILE: /run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: on-failure

  pgadmin:
    container_name: "pgAdmin4"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-db

volumes:
  postgres-data:
  pgadmin-data: