version: "2.3"

services:
  postgres-db:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory
      # POSTGRES_PASSWORD_FILE: /run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  pgadmin:
    container_name: "pgAdmin4"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-db

  inventory-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory:latest
    container_name: inventory
    depends_on:
      - postgres-db
    environment:
      DATABASE_PASSWORD: root
      DATABASE_USERNAME: postgres
      DATABASE_HOSTNAME: postgres-db
      DATABASE_PORT: 5432
      DATABASE_NAME: inventory
    restart: on-failure
    ports:
      - "8000:8000"
    expose:
      - 8000

  inventory-app-ui:
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    image: inventory-ui:latest
    container_name: inventory-ui
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - inventory-app

volumes:
  pgadmin-data:
  postgres-data: